FROM ubuntu:quantal
MAINTAINER Buodaxuo8IeS MoGh4aaQuaij@yandex.com
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y git mercurial gcc flex bison
RUN /bin/bash -c "cd /usr/local/ && hg clone -u release https://code.google.com/p/go && cd go/src && ./all.bash"

RUN /bin/bash -c "GOPATH=/usr/local/ /usr/local/go/bin/go get github.com/Buodaxuo8IeS/hello"
EXPOSE :8080
CMD /usr/local/bin/hello
ENV GOPATH /usr/local
